---
- name: Fail if required Readeck settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - readeck_identifier
    - readeck_uid
    - readeck_gid
    - readeck_hostname
    - readeck_path_prefix
    - readeck_container_network

- when: readeck_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Readeck Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - readeck_container_labels_traefik_hostname
        - readeck_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `readeck_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if readeck_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          readeck_container_labels_traefik_path_prefix (`{{ readeck_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/readeck`).
      when: "readeck_container_labels_traefik_path_prefix != '/' and readeck_container_labels_traefik_path_prefix[-1] == '/'"
